import math  # [DIM 1536]
import os  # [EMBED FIX]
from unittest.mock import AsyncMock, MagicMock, patch  # [EMBED FIX]

import pytest  # [EMBED FIX]
from google.genai import types  # [EMBED FIX]

from app.core.config import settings  # [EMBED FIX]
from app.engines.embedder import (  # [EMBED FIX]
    EmbeddingError,  # [EMBED FIX]
    GeminiEmbeddingEngine,  # [EMBED FIX]
    gemini_embedder,  # [EMBED FIX]
)  # [EMBED FIX]


def test_prefix_verification_and_no_double_prefixing():  # [EMBED FIX]
    """Verify document and query text formatting, including title handling and idempotency."""  # [EMBED FIX]
    # Query prefixing  # [EMBED FIX]
    q1 = GeminiEmbeddingEngine.format_text("paracetamol mechanism", kind="query")  # [EMBED FIX]
    assert q1 == "task: search result | query: paracetamol mechanism"  # [EMBED FIX]
    # [EMBED FIX]
    q2 = GeminiEmbeddingEngine.format_text(q1, kind="query")  # [EMBED FIX]
    assert q2 == q1  # [EMBED FIX]
    # [EMBED FIX]
    # Document prefixing without title  # [EMBED FIX]
    d1 = GeminiEmbeddingEngine.format_text(
        "paracetamol dosage is 500mg", kind="document"
    )  # [EMBED FIX]
    assert d1 == "title: none | text: paracetamol dosage is 500mg"  # [EMBED FIX]
    # [EMBED FIX]
    # Document prefixing with title  # [EMBED FIX]
    d2 = GeminiEmbeddingEngine.format_text(  # [EMBED FIX]
        "paracetamol dosage is 500mg",
        kind="document",
        title="British National Formulary",  # [EMBED FIX]
    )  # [EMBED FIX]
    assert (
        d2 == "title: British National Formulary | text: paracetamol dosage is 500mg"
    )  # [EMBED FIX]
    # [EMBED FIX]
    # Idempotent document prefixing  # [EMBED FIX]
    d3 = GeminiEmbeddingEngine.format_text(d2, kind="document", title="Other Title")  # [EMBED FIX]
    assert d3 == d2  # [EMBED FIX]


# [EMBED FIX]
# [EMBED FIX]
@pytest.mark.asyncio  # [EMBED FIX]
async def test_embed_batch_calls_wrapped_content_objects(monkeypatch):  # [EMBED FIX]
    """Verify each batch makes one client call with types.Content objects."""  # [EMBED FIX]
    monkeypatch.setattr(settings, "EMBEDDER_FAKE_MODE", False)  # [EMBED FIX]
    monkeypatch.setattr(settings, "GEMINI_API_KEY", "test-key-mock")  # [EMBED FIX]
    # [EMBED FIX]
    mock_response = MagicMock()  # [EMBED FIX]
    mock_emb1 = MagicMock(values=[0.1] * settings.GEMINI_EMBEDDING_DIMENSIONS)  # [DIM 1536]
    mock_emb2 = MagicMock(values=[0.2] * settings.GEMINI_EMBEDDING_DIMENSIONS)  # [DIM 1536]
    mock_response.embeddings = [mock_emb1, mock_emb2]  # [EMBED FIX]
    # [EMBED FIX]
    mock_client = MagicMock()  # [EMBED FIX]
    mock_client.aio.models.embed_content = AsyncMock(return_value=mock_response)  # [EMBED FIX]
    # [EMBED FIX]
    with patch("google.genai.Client", return_value=mock_client):  # [EMBED FIX]
        engine = GeminiEmbeddingEngine()  # [EMBED FIX]
        texts = ["Text item 1", "Text item 2"]  # [EMBED FIX]
        vectors = await engine.embed_batch(texts, kind="document")  # [EMBED FIX]
        # [EMBED FIX]
        assert len(vectors) == 2  # [EMBED FIX]
        assert len(vectors[0]) == settings.GEMINI_EMBEDDING_DIMENSIONS  # [DIM 1536]
        assert mock_client.aio.models.embed_content.call_count == 1  # [EMBED FIX]
        # [EMBED FIX]
        _, kwargs = mock_client.aio.models.embed_content.call_args  # [EMBED FIX]
        contents = kwargs["contents"]  # [EMBED FIX]
        assert len(contents) == 2  # [EMBED FIX]
        assert isinstance(contents[0], types.Content)  # [EMBED FIX]
        assert contents[0].parts[0].text == "title: none | text: Text item 1"  # [EMBED FIX]
        assert contents[1].parts[0].text == "title: none | text: Text item 2"  # [EMBED FIX]
        assert (
            kwargs["config"].output_dimensionality == settings.GEMINI_EMBEDDING_DIMENSIONS
        )  # [DIM 1536]


# [EMBED FIX]
# [EMBED FIX]
@pytest.mark.asyncio  # [EMBED FIX]
async def test_embed_batch_raising_exception_raises_embedding_error(monkeypatch):  # [EMBED FIX]
    """Verify EMBEDDER_FAKE_MODE=False + client failure raises EmbeddingError."""  # [EMBED FIX]
    monkeypatch.setattr(settings, "EMBEDDER_FAKE_MODE", False)  # [EMBED FIX]
    monkeypatch.setattr(settings, "GEMINI_API_KEY", "test-key-mock")  # [EMBED FIX]
    # [EMBED FIX]
    mock_client = MagicMock()  # [EMBED FIX]
    mock_client.aio.models.embed_content = AsyncMock(  # [EMBED FIX]
        side_effect=RuntimeError("Simulated unrecoverable API error")  # [EMBED FIX]
    )  # [EMBED FIX]
    # [EMBED FIX]
    with patch("google.genai.Client", return_value=mock_client):  # [EMBED FIX]
        engine = GeminiEmbeddingEngine()  # [EMBED FIX]
        with pytest.raises(EmbeddingError, match="Non-retryable embedding failure"):  # [EMBED FIX]
            await engine.embed_batch(["Sample text"], kind="query")  # [EMBED FIX]


# [EMBED FIX]
# [EMBED FIX]
@pytest.mark.asyncio  # [EMBED FIX]
async def test_embed_batch_count_mismatch_raises_embedding_error(monkeypatch):  # [EMBED FIX]
    """Verify wrong number of embeddings in response raises EmbeddingError."""  # [EMBED FIX]
    monkeypatch.setattr(settings, "EMBEDDER_FAKE_MODE", False)  # [EMBED FIX]
    monkeypatch.setattr(settings, "GEMINI_API_KEY", "test-key-mock")  # [EMBED FIX]
    # [EMBED FIX]
    mock_response = MagicMock()  # [DIM 1536]
    mock_response.embeddings = [
        MagicMock(values=[0.1] * settings.GEMINI_EMBEDDING_DIMENSIONS)
    ]  # Only 1 embedding returned  # [DIM 1536]
    mock_client = MagicMock()  # [DIM 1536]
    mock_client.aio.models.embed_content = AsyncMock(return_value=mock_response)  # [DIM 1536]
    with patch("google.genai.Client", return_value=mock_client):  # [DIM 1536]
        engine = GeminiEmbeddingEngine()  # [DIM 1536]
        with pytest.raises(
            EmbeddingError, match="Embedding count mismatch: expected 2, got 1"
        ):  # [DIM 1536]
            await engine.embed_batch(["First text", "Second text"], kind="query")  # [DIM 1536]


# [DIM 1536]
# [DIM 1536]
@pytest.mark.asyncio  # [DIM 1536]
async def test_embed_batch_dimension_mismatch_raises_embedding_error(monkeypatch):  # [DIM 1536]
    """Verify wrong vector dimension in response raises EmbeddingError."""  # [DIM 1536]
    monkeypatch.setattr(settings, "EMBEDDER_FAKE_MODE", False)  # [DIM 1536]
    monkeypatch.setattr(settings, "GEMINI_API_KEY", "test-key-mock")  # [DIM 1536]
    mismatch_dim = settings.GEMINI_EMBEDDING_DIMENSIONS // 2  # [DIM 1536]
    mock_response = MagicMock()  # [DIM 1536]
    mock_response.embeddings = [
        MagicMock(values=[0.1] * mismatch_dim)
    ]  # Half dimension mismatch  # [DIM 1536]
    mock_client = MagicMock()  # [DIM 1536]
    mock_client.aio.models.embed_content = AsyncMock(return_value=mock_response)  # [DIM 1536]
    with patch("google.genai.Client", return_value=mock_client):  # [DIM 1536]
        engine = GeminiEmbeddingEngine()  # [DIM 1536]
        with pytest.raises(  # [DIM 1536]
            EmbeddingError,  # [DIM 1536]
            match=f"Vector dimension mismatch: expected {settings.GEMINI_EMBEDDING_DIMENSIONS}, got {mismatch_dim}",  # [DIM 1536]
        ):  # [DIM 1536]
            await engine.embed_batch(["Sample text"], kind="document")  # [DIM 1536]


# [DIM 1536]
# [DIM 1536]
@pytest.mark.live  # [DIM 1536]
@pytest.mark.asyncio  # [DIM 1536]
@pytest.mark.skipif(  # [DIM 1536]
    os.getenv("RUN_LIVE_EMBED_TEST") != "1",  # [DIM 1536]
    reason="Live embed test requires RUN_LIVE_EMBED_TEST=1",  # [DIM 1536]
)  # [DIM 1536]
async def test_live_embedder_call(monkeypatch):  # [DIM 1536]
    """Live smoke test against Google AI Studio using real GEMINI_API_KEY."""  # [DIM 1536]
    monkeypatch.setattr(settings, "EMBEDDER_FAKE_MODE", False)  # [DIM 1536]
    texts = [  # [DIM 1536]
        "PansGPT live smoke test embedding call 1",  # [DIM 1536]
        "Pharmacology of paracetamol and its metabolites",  # [DIM 1536]
        "Clinical pharmacokinetics and dosage guidelines",  # [DIM 1536]
    ]  # [DIM 1536]
    vectors = await gemini_embedder.embed_batch(texts, kind="document")  # [DIM 1536]
    assert len(vectors) == 3  # [DIM 1536]
    for vec in vectors:  # [DIM 1536]
        assert len(vec) == settings.GEMINI_EMBEDDING_DIMENSIONS  # [DIM 1536]
        assert all(isinstance(v, float) for v in vec)  # [DIM 1536]
        norm = math.sqrt(sum(v * v for v in vec))  # [DIM 1536]
        assert abs(norm - 1.0) < 1e-3  # [DIM 1536]
