-- ============================================================================== -- [DIM 1536]
-- Migration: 20261010030000_embedding_1536.sql -- [DIM 1536]
-- Purpose: Change embedding dimension from 3072 to 1536 across document_chunks -- [DIM 1536]
-- Model: gemini-embedding-2 (1536 dimensions) -- [DIM 1536]
-- ============================================================================== -- [DIM 1536]
-- -- [DIM 1536]
-- Preflight Checks (Run manually if needed): -- [DIM 1536]
-- SELECT count(*) AS chunk_count FROM public.document_chunks; -- [DIM 1536]
-- SELECT count(*) AS document_count FROM public.documents; -- [DIM 1536]
-- -- [DIM 1536]
BEGIN; -- [DIM 1536]
-- -- [DIM 1536]
-- 1. Drop existing HNSW vector index -- [DIM 1536]
DROP INDEX IF EXISTS public.idx_document_chunks_hnsw; -- [DIM 1536]
-- -- [DIM 1536]
-- 2. Purge existing chunks (vectors cannot be cast across dimensions) -- [DIM 1536]
TRUNCATE TABLE public.document_chunks; -- [DIM 1536 FIX]
-- -- [DIM 1536]
-- 3. Reset document embedding state to pending for worker re-ingestion -- [DIM 1536 FIX]
UPDATE public.documents -- [DIM 1536 FIX]
SET embedding_status = 'pending', -- [DIM 1536 FIX]
    embedding_progress = 0, -- [DIM 1536 FIX]
    total_chunks = 0, -- [DIM 1536 FIX]
    ingestion_lock_id = NULL, -- [DIM 1536 FIX]
    ingestion_heartbeat = NULL -- [DIM 1536 FIX]
WHERE deleted_at IS NULL; -- [DIM 1536 FIX]
-- -- [DIM 1536]
-- 4. Alter column embedding to vector(1536) -- [DIM 1536]
ALTER TABLE public.document_chunks -- [DIM 1536]
  ALTER COLUMN embedding TYPE vector(1536); -- [DIM 1536]
-- -- [DIM 1536]
-- 5. Recreate HNSW index using halfvec(1536) cosine ops -- [DIM 1536]
CREATE INDEX idx_document_chunks_hnsw -- [DIM 1536]
  ON public.document_chunks -- [DIM 1536]
  USING hnsw ((embedding::halfvec(1536)) halfvec_cosine_ops); -- [DIM 1536]
-- -- [DIM 1536]
-- 6. Drop and recreate match_documents_hybrid with vector(1536) -- [DIM 1536]
DROP FUNCTION IF EXISTS public.match_documents_hybrid(text, vector(3072), double precision, integer, uuid, public.university_level[], uuid[]); -- [DIM 1536]
DROP FUNCTION IF EXISTS public.match_documents_hybrid(text, vector(1536), double precision, integer, uuid, public.university_level[], uuid[]); -- [DIM 1536]
DROP FUNCTION IF EXISTS public.match_documents_hybrid(text, vector, double precision, integer, uuid, public.university_level[], uuid[]); -- [DIM 1536]
-- -- [DIM 1536]
CREATE OR REPLACE FUNCTION public.match_documents_hybrid( -- [DIM 1536]
    query_text text, -- [DIM 1536]
    query_embedding vector(1536), -- [DIM 1536]
    match_threshold double precision DEFAULT 0.25, -- [DIM 1536]
    match_count integer DEFAULT 10, -- [DIM 1536]
    filter_university_id uuid DEFAULT NULL, -- [DIM 1536]
    filter_levels public.university_level[] DEFAULT NULL, -- [DIM 1536]
    filter_doc_ids uuid[] DEFAULT NULL -- [DIM 1536]
) -- [DIM 1536]
RETURNS TABLE ( -- [DIM 1536]
    chunk_id uuid, -- [DIM 1536]
    document_id uuid, -- [DIM 1536]
    chunk_index integer, -- [DIM 1536]
    content text, -- [DIM 1536]
    content_type text, -- [DIM 1536]
    page_start integer, -- [DIM 1536]
    page_end integer, -- [DIM 1536]
    bounding_box jsonb, -- [DIM 1536]
    section_id uuid, -- [DIM 1536]
    segment_id uuid, -- [DIM 1536]
    dense_score double precision, -- [DIM 1536]
    fts_score double precision, -- [DIM 1536]
    trgm_score double precision, -- [DIM 1536]
    rrf_score double precision -- [DIM 1536]
) -- [DIM 1536]
LANGUAGE plpgsql STABLE -- [DIM 1536]
AS $$ -- [DIM 1536]
DECLARE -- [DIM 1536]
    k CONSTANT double precision := 60.0; -- [DIM 1536]
BEGIN -- [DIM 1536]
    RETURN QUERY -- [DIM 1536]
    WITH -- [DIM 1536]
    candidate_docs AS ( -- [DIM 1536]
        SELECT d.id -- [DIM 1536]
        FROM public.documents d -- [DIM 1536]
        WHERE d.deleted_at IS NULL -- [DIM 1536]
          AND d.status = 'active' -- [DIM 1536]
          AND (filter_university_id IS NULL OR d.university_id = filter_university_id) -- [DIM 1536]
          AND (filter_doc_ids IS NULL OR d.id = ANY(filter_doc_ids)) -- [DIM 1536]
    ), -- [DIM 1536]
    vector_pool AS ( -- [DIM 1536]
        SELECT -- [DIM 1536]
            c.id, -- [DIM 1536]
            1.0 - ((c.embedding::halfvec(1536)) <=> (query_embedding::halfvec(1536))) AS score, -- [DIM 1536]
            ROW_NUMBER() OVER (ORDER BY ((c.embedding::halfvec(1536)) <=> (query_embedding::halfvec(1536))) ASC) AS rank -- [DIM 1536]
        FROM public.document_chunks c -- [DIM 1536]
        JOIN candidate_docs cd ON cd.id = c.document_id -- [DIM 1536]
        WHERE c.embedding IS NOT NULL -- [DIM 1536]
          AND (1.0 - ((c.embedding::halfvec(1536)) <=> (query_embedding::halfvec(1536)))) >= match_threshold -- [DIM 1536]
        ORDER BY (c.embedding::halfvec(1536)) <=> (query_embedding::halfvec(1536)) ASC -- [DIM 1536]
        LIMIT 40 -- [DIM 1536]
    ), -- [DIM 1536]
    fts_pool AS ( -- [DIM 1536]
        SELECT -- [DIM 1536]
            c.id, -- [DIM 1536]
            ts_rank_cd(c.content_fts, plainto_tsquery('english', query_text))::double precision AS score, -- [DIM 1536]
            ROW_NUMBER() OVER (ORDER BY ts_rank_cd(c.content_fts, plainto_tsquery('english', query_text)) DESC) AS rank -- [DIM 1536]
        FROM public.document_chunks c -- [DIM 1536]
        JOIN candidate_docs cd ON cd.id = c.document_id -- [DIM 1536]
        WHERE c.content_fts @@ plainto_tsquery('english', query_text) -- [DIM 1536]
        ORDER BY score DESC -- [DIM 1536]
        LIMIT 40 -- [DIM 1536]
    ), -- [DIM 1536]
    trgm_pool AS ( -- [DIM 1536]
        SELECT -- [DIM 1536]
            c.id, -- [DIM 1536]
            word_similarity(query_text, c.content)::double precision AS score, -- [DIM 1536]
            ROW_NUMBER() OVER (ORDER BY word_similarity(query_text, c.content) DESC) AS rank -- [DIM 1536]
        FROM public.document_chunks c -- [DIM 1536]
        JOIN candidate_docs cd ON cd.id = c.document_id -- [DIM 1536]
        WHERE word_similarity(query_text, c.content) >= 0.20 -- [DIM 1536]
        ORDER BY score DESC -- [DIM 1536]
        LIMIT 40 -- [DIM 1536]
    ), -- [DIM 1536]
    combined_ids AS ( -- [DIM 1536]
        SELECT id FROM vector_pool -- [DIM 1536]
        UNION -- [DIM 1536]
        SELECT id FROM fts_pool -- [DIM 1536]
        UNION -- [DIM 1536]
        SELECT id FROM trgm_pool -- [DIM 1536]
    ), -- [DIM 1536]
    ranked_chunks AS ( -- [DIM 1536]
        SELECT -- [DIM 1536]
            cid.id, -- [DIM 1536]
            COALESCE(vp.score, 0.0) AS dense_score, -- [DIM 1536]
            COALESCE(fp.score, 0.0) AS fts_score, -- [DIM 1536]
            COALESCE(tp.score, 0.0) AS trgm_score, -- [DIM 1536]
            ( -- [DIM 1536]
                COALESCE(1.0 / (k + vp.rank), 0.0) + -- [DIM 1536]
                COALESCE(1.0 / (k + fp.rank), 0.0) + -- [DIM 1536]
                COALESCE(1.0 / (k + tp.rank), 0.0) -- [DIM 1536]
            ) AS rrf_score -- [DIM 1536]
        FROM combined_ids cid -- [DIM 1536]
        LEFT JOIN vector_pool vp ON vp.id = cid.id -- [DIM 1536]
        LEFT JOIN fts_pool fp ON fp.id = cid.id -- [DIM 1536]
        LEFT JOIN trgm_pool tp ON tp.id = cid.id -- [DIM 1536]
    ) -- [DIM 1536]
    SELECT -- [DIM 1536]
        c.id AS chunk_id, -- [DIM 1536]
        c.document_id, -- [DIM 1536]
        c.chunk_index, -- [DIM 1536]
        c.content, -- [DIM 1536]
        'text'::text AS content_type, -- [DIM 1536]
        c.page_start, -- [DIM 1536]
        c.page_end, -- [DIM 1536]
        c.bounding_box, -- [DIM 1536]
        NULL::uuid AS section_id, -- [DIM 1536]
        c.segment_id, -- [DIM 1536]
        rc.dense_score, -- [DIM 1536]
        rc.fts_score, -- [DIM 1536]
        rc.trgm_score, -- [DIM 1536]
        rc.rrf_score -- [DIM 1536]
    FROM ranked_chunks rc -- [DIM 1536]
    JOIN public.document_chunks c ON c.id = rc.id -- [DIM 1536]
    ORDER BY rc.rrf_score DESC -- [DIM 1536]
    LIMIT match_count; -- [DIM 1536]
END; -- [DIM 1536]
$$; -- [DIM 1536]
-- -- [DIM 1536]
-- 7. Drop and recreate match_document_chunks with vector(1536) -- [DIM 1536]
DROP FUNCTION IF EXISTS public.match_document_chunks(vector(3072), double precision, integer, uuid); -- [DIM 1536]
DROP FUNCTION IF EXISTS public.match_document_chunks(vector(1536), double precision, integer, uuid); -- [DIM 1536]
DROP FUNCTION IF EXISTS public.match_document_chunks(vector, double precision, integer, uuid); -- [DIM 1536]
-- -- [DIM 1536]
CREATE OR REPLACE FUNCTION public.match_document_chunks( -- [DIM 1536]
  query_embedding vector(1536), -- [DIM 1536]
  match_threshold double precision, -- [DIM 1536]
  match_count integer, -- [DIM 1536]
  doc_id uuid -- [DIM 1536]
) -- [DIM 1536]
RETURNS TABLE ( -- [DIM 1536]
  id uuid, -- [DIM 1536]
  document_id uuid, -- [DIM 1536]
  content text, -- [DIM 1536]
  page_start integer, -- [DIM 1536]
  page_end integer, -- [DIM 1536]
  chunk_index integer, -- [DIM 1536]
  similarity double precision, -- [DIM 1536]
  bounding_box jsonb -- [DIM 1536]
) -- [DIM 1536]
LANGUAGE sql STABLE -- [DIM 1536]
AS $$ -- [DIM 1536]
  SELECT -- [DIM 1536]
    dc.id, -- [DIM 1536]
    dc.document_id, -- [DIM 1536]
    dc.content, -- [DIM 1536]
    dc.page_start, -- [DIM 1536]
    dc.page_end, -- [DIM 1536]
    dc.chunk_index, -- [DIM 1536]
    1.0 - ((dc.embedding::halfvec(1536)) <=> (query_embedding::halfvec(1536))) AS similarity, -- [DIM 1536]
    dc.bounding_box -- [DIM 1536]
  FROM public.document_chunks dc -- [DIM 1536]
  WHERE dc.document_id = doc_id -- [DIM 1536]
    AND dc.embedding IS NOT NULL -- [DIM 1536]
    AND 1.0 - ((dc.embedding::halfvec(1536)) <=> (query_embedding::halfvec(1536))) >= match_threshold -- [DIM 1536]
  ORDER BY (dc.embedding::halfvec(1536)) <=> (query_embedding::halfvec(1536)) ASC -- [DIM 1536]
  LIMIT match_count; -- [DIM 1536]
$$; -- [DIM 1536]
-- -- [DIM 1536]
-- 8. Drop and recreate match_documents_global with vector(1536) -- [DIM 1536]
DROP FUNCTION IF EXISTS public.match_documents_global(vector(3072), double precision, integer, uuid[]); -- [DIM 1536]
DROP FUNCTION IF EXISTS public.match_documents_global(vector(1536), double precision, integer, uuid[]); -- [DIM 1536]
DROP FUNCTION IF EXISTS public.match_documents_global(vector, double precision, integer, uuid[]); -- [DIM 1536]
-- -- [DIM 1536]
CREATE OR REPLACE FUNCTION public.match_documents_global( -- [DIM 1536]
  query_embedding vector(1536), -- [DIM 1536]
  match_threshold double precision, -- [DIM 1536]
  match_count integer, -- [DIM 1536]
  doc_ids uuid[] -- [DIM 1536]
) -- [DIM 1536]
RETURNS TABLE ( -- [DIM 1536]
  id uuid, -- [DIM 1536]
  document_id uuid, -- [DIM 1536]
  content text, -- [DIM 1536]
  page_start integer, -- [DIM 1536]
  page_end integer, -- [DIM 1536]
  chunk_index integer, -- [DIM 1536]
  similarity double precision -- [DIM 1536]
) -- [DIM 1536]
LANGUAGE sql STABLE -- [DIM 1536]
AS $$ -- [DIM 1536]
  SELECT -- [DIM 1536]
    dc.id, -- [DIM 1536]
    dc.document_id, -- [DIM 1536]
    dc.content, -- [DIM 1536]
    dc.page_start, -- [DIM 1536]
    dc.page_end, -- [DIM 1536]
    dc.chunk_index, -- [DIM 1536]
    1.0 - ((dc.embedding::halfvec(1536)) <=> (query_embedding::halfvec(1536))) AS similarity -- [DIM 1536]
  FROM public.document_chunks dc -- [DIM 1536]
  WHERE dc.document_id = ANY(doc_ids) -- [DIM 1536]
    AND 1.0 - ((dc.embedding::halfvec(1536)) <=> (query_embedding::halfvec(1536))) >= match_threshold -- [DIM 1536]
  ORDER BY (dc.embedding::halfvec(1536)) <=> (query_embedding::halfvec(1536)) ASC -- [DIM 1536]
  LIMIT match_count; -- [DIM 1536]
$$; -- [DIM 1536]
-- -- [DIM 1536]
COMMIT; -- [DIM 1536]
-- -- [DIM 1536]
-- Post-migration Verification Queries (Run manually in Supabase SQL editor): -- [DIM 1536]
-- SELECT column_name, data_type, udt_name FROM information_schema.columns WHERE table_name = 'document_chunks' AND column_name = 'embedding'; -- [DIM 1536]
-- SELECT indexname, indexdef FROM pg_indexes WHERE tablename = 'document_chunks' AND indexname = 'idx_document_chunks_hnsw'; -- [DIM 1536]
-- SELECT proname, proargnames FROM pg_proc WHERE proname IN ('match_documents_hybrid', 'match_document_chunks', 'match_documents_global'); -- [DIM 1536]
-- Smoke test post-apply: -- [DIM 1536 FIX]
-- SELECT count(*) FROM public.match_documents_hybrid('test', array_fill(0::real, ARRAY[1536])::vector, 0.0, 5, NULL, NULL, NULL); -- [DIM 1536 FIX]
